[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
clap = { version = "4.5.53", features = ["derive"] }
itertools = "0.14.0"
num = "0.4.3"
rayon = "1.11.0"
regex = "1.12.2"
